pipelines:
  split_join:
    settings:
      event_timeout: 1h
    input:
      type: file
      offsets_op: reset
    actions:
      - type: split
        field: data
      - type: join
        field: message
        start: '/^start/'
        continue: '/^continue/'
      - type: modify
        service: splitter
      - type: rename
        service: 'k8s_pod_label_app'
    output:
      type: file
