pipelines:
  kafka_gelf_example:
    input:
      type: kafka
      brokers: [ kafka-broker-0.svc.local, kafka-broker-1.svc.local, kafka-broker-2.svc.local ]
      topics: [ k8s-logs ]

    actions:
      - type: json_decode                             # unpack "log" field
        field: log
        metric_name: input
        metric_labels: [ k8s_label_app ]                # expose input metrics to prometheus

      # normalize                                     # unify log format
      - type: rename
        log: message
        msg: message
        ts: time
        _ts: time
        systemd.unit: service
        syslog.identifier: service
        k8s_label_app: service

    output:
      type: gelf
      endpoint: "graylog.svc.cluster.local:12201"
      reconnect_interval: 1m
      default_short_message_value: "message isn't provided"
